# configure some default settings
[default]
sqlalchemy_database_uri = "sqlite:///myblog.sqlite"
sqlalchemy_track_modifications = false
confirmation_link_timeout = 12   # in hours
password_reset_timeout = 10   # in minutes

# configure the development environment settings
[development]
flask_debug = true
extensions = ["flask_debugtoolbar:DebugToolbarExtension"]
debug_tb_enabled = false
debug_tb_intercept_redirects = false
logging_level = "DEBUG"

# development database settings
sqlalchemy_echo = false

# configure the production environment settings
[production]
flask_debug = false
logging_level = "INFO"

# production database settings
sqlalchemy_echo = false
